# Generated by Django 5.2.17 on 2026-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=200, unique=True)),
                ('ville_depart', models.CharField(max_length=200, unique=True)),
                ('ville_arrive', models.CharField(max_length=200, unique=True)),
                ('poids_kg', models.FloatField()),
                ('date_souhaitee', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=200)),
                ('statut', models.CharField(choices=[('A', 'online'), ('B', 'offline')], default='A')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
