# Generated by Django 5.2.17 on 2026-10-06 15:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0004_alter_entreprise_adresse_and_more'),
        ('ExpeditionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedition',
            name='entreprise',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='EntrepriseApp.entreprise'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expedition',
            name='date_souhaitee',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='poids_kg',
            field=models.DecimalField(decimal_places=3, max_digits=10, validators=[django.core.validators.MinValueValidator(0.001, 'Le poids doit être supérieur à 0 kg')]),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='reference',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'en_attente'), ('t', 'terminee'), ('a', 'annulee')], max_length=100),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='ville_arrive',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='ville_depart',
            field=models.CharField(max_length=80),
        ),
    ]
