# Generated by Django 5.2.17 on 2026-10-06 13:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, 'l adresse doit contenir au moins 20 caractere '), django.core.validators.MaxLengthValidator(400, 'l adrresse ne peur pas depaassser 4000 caractere ')]),
        ),
    ]
