# Generated by Django 5.2.17 on 2026-10-06 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EntrepriseApp', '0003_alter_utilisateur_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entreprise',
            name='adresse',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20, "L'adresse doit avoir au moins 20 caractères"), django.core.validators.MaxLengthValidator(400, "L'adresse ne peut pas dépasser 400 caractères")]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='matricule_fiscale',
            field=models.CharField(max_length=17, unique=True, validators=[django.core.validators.RegexValidator(message='format erroné', regex='^\\d{7}[/ -]?[A-Za-z][/ -]?[ABDNPEabdnpe][/ -]?[MPCNEmpcne][/ -]?\\d{3}$')]),
        ),
        migrations.AlterField(
            model_name='entreprise',
            name='type_entreprise',
            field=models.CharField(choices=[('c', 'Chargeur'), ('t', 'Transporteur')], default='c', max_length=100),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('c', 'Chargeur'), ('t', 'Transporteur')], default='c', max_length=20),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='user_id',
            field=models.CharField(editable=False, max_length=8, primary_key=True, serialize=False),
        ),
    ]
