# Generated by Django 5.2.17 on 2026-09-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=200, unique=True)),
                ('type_vehicule', models.CharField(choices=[('f', 'electrique'), ('t', 'hybride')], default='f')),
                ('capacite_kg', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
